### ISSUE TITLE
Open Hack Rotterdam

### ISSUE THREAD

**Issue by jgroenen** [OpenHack/openhack.github.com#325]
Hi, I'm starting an Open Hack Meetup in Rotterdam, the Netherlands. www.openhack.nl
Can you add us to the website? Thnx!

**Comment by duggiefresh** [comment]
Hello @jgroenen, we're pretty excited for Rotterdam's Open Hack!

Since we're open sourced, you can add Rotterdam's meetup with a PR. :)

Here's the quick guide: https://github.com/OpenHack/openhack.github.com/blob/master/yours/index.markdown

**Comment by friedger** [comment]
If you need more help with the pull request please open a new issue.
