### ISSUE TITLE
Slack (or other) chat?

### ISSUE THREAD

**Issue by pjaspers** [OpenHack/openhack.github.com#328]
We (try to) run the OpenHack in Belgium, and one of the things we're struggling with each time is setting up a chat room for all participants of that OpenHack.

We used to do a shared Campfire room, then we used a room in Kato, but since Slack is now the new hotness @To1ne had a pretty great idea: 1 Slack account shared across all openhacks with a room for each OpenHack.

So this way all participants across the globe could chat with each other, or just watch and chat in the room of that OpenHack.

Thoughts?

**Comment by friedger** [comment]
What about gitter? I like it because it is related to the github repo. And
rooms can be setup for organisations as well.
Am 20.05.2015 00:27 schrieb "Piet Jaspers" <notifications@github.com>:

**Comment by pjaspers** [comment]
We went the gitter way: https://gitter.im/10to1/openhack.github.com
