### ISSUE TITLE
"What is OpenHack?" section is empty in case a user do not have Flash player installed

### ISSUE THREAD

**Issue by synaptiko** [OpenHack/openhack.github.com#347]
Hi,

great initiative and I'm really thinking about starting organizing local events in Pilsen/Czech Republic... but as I don't have Flash player installed anymore (because of lot of security issues found recently) I'm not able to see what's in main section of your web. I've tried to "derive" Youtube's watch URL from source code of the page, but it doesn't work: https://www.youtube.com/watch?v=bQgbSXBjpz0.

What about to use embed code which Youtube gives for newer videos:
```html
<iframe width="560" height="315" src="https://www.youtube.com/embed/bQgbSXBjpz0" frameborder="0" allowfullscreen></iframe>
```
(btw. video is not working even if I used this code, so something with it is definitely wrong).

Thanks...

**Comment by ilikepi** [comment]
Thanks for the report!
