### ISSUE TITLE
Interested in some type of technology sponsorship?

### ISSUE THREAD

**Issue by rhyolight** [OpenHack/openhack.github.com#350]
Hi @qrush! I just saw your video at http://openhack.github.io/ and I think this is a really great initiative. I love hackathons, and I've planned several over the past few years. 

I'm the community manager of several [open](https://github.com/numenta) [source](https://github.com/nupic-community) projects that can provide some interesting tech for your hackathons. We deal in a new kind of machine intelligence created with [very close adherence to the biology of the human neocortex](http://numenta.com/learn/). I'm looking for ways we can make our open source tools available to hackathons around the world, and I was just wondering if you were interested in something like this?

Thanks for your time, and here's a gif for your collection!

![big happy dog](https://s3.amazonaws.com/uploads.hipchat.com/11455/64377/CK7oOGSd5v585wu/OvggWKr.gif)

**Comment by friedger** [comment]
I think we can close this by now. Feel free to reach out to individual organisers.
