### ISSUE TITLE
Maintainer?

### ISSUE THREAD

**Issue by jarednorman** [OpenHack/openhack.github.com#383]
I'm the organizer for the OpenHack chapter in Victoria, BC, Canada. I'm not the original organizer, but we've been running since the summer of 2013. We still meet weekly and have even recovered to reasonable attendance numbers since things opened up again.

I've got a couple open PRs here that haven't got any attention recently. I'm happy to assist with the maintenance of the OpenHack site, handle open issues, merge PRs, if that help is wanted/needed. Just let me know.

**Comment by friedger** [comment]
Merged

**Comment by jarednorman** [comment]
That works too! Thanks!
